<a href="https://colab.research.google.com/github/Antoni018/inteligenciaArtificial/blob/main/01-07-2027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[0], a[1])
print(a[0:2])
print(a[1:])

a[1]=888
print(a)


(3,)
<class 'numpy.ndarray'>
[11 22 33]
11 22
[11 22]
[22 33]
[ 11 888  33]


In [ ]:
b=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(b.shape)
print(type(b))
print(b)

print(b[1,1])
aux=b[1:,1:].copy()
print(aux.shape)
print(aux)

print('ANTES....')
print(b)
print(aux)

aux[1,1]=1000

print('DESPUES...')
print(b)
print(aux)

(3, 3)
<class 'numpy.ndarray'>
[[11 22 33]
 [44 55 66]
 [77 88 99]]
55
(2, 2)
[[55 66]
 [88 99]]
ANTES....
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[55 66]
 [88 99]]
DESPUES...
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[  55   66]
 [  88 1000]]


In [ ]:
c=np.zeros((4,4))
print(c)
print(c.shape)

d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [ ]:
  e=np.eye(3,3)
  print(e)
  f=np.ones((4,5))
  print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
g=np.random.random((5,5))
print(g)

[[0.24159987 0.17052845 0.21724934 0.42790918 0.4819766 ]
 [0.766621   0.25667367 0.13332506 0.44989292 0.26028065]
 [0.43672544 0.57427573 0.68819656 0.89324545 0.49721416]
 [0.47286933 0.83208935 0.65665585 0.59581535 0.1716983 ]
 [0.03341136 0.86405876 0.05365493 0.78496892 0.11614335]]


In [ ]:
tmp1=np.random.randint(1,21, size=(4,4))
print(tmp1)
rows=np.array([0,1,2,0])
cols=np.arange(4)

print(rows)
print(cols)



[[ 5 16  1 11]
 [18  8 14 14]
 [18  4 15  3]
 [13  1 19  1]]
[0 1 2 0]
[0 1 2 3]


In [ ]:
tmp1[rows, cols]=100
print(tmp1)

[[100  16   1 100]
 [ 18 100  14  14]
 [ 18   4 100   3]
 [ 13   1  19   1]]


In [ ]:
tmp2=np.random.randint(20,50, size=(6,6))
print(tmp2)

[[32 33 27 34 28 35]
 [48 47 45 48 29 33]
 [47 26 45 29 45 22]
 [27 34 40 42 28 47]
 [27 27 26 42 37 28]
 [46 26 39 30 41 29]]


In [ ]:
mask = tmp2 > 45
print(mask)
elemay = tmp2[mask]

print("Elementos mayores a 45:")
print(elemay)

[[False False False False False False]
 [ True  True False  True False False]
 [ True False False False False False]
 [False False False False False  True]
 [False False False False False False]
 [ True False False False False False]]
Elementos mayores a 45:
[48 47 48 47 47 46]


In [ ]:
tmp3=np.random.randint(1,100, size=(10,10))
print(tmp3)

[[70 58 13 87 22 42 11 44 76 37]
 [ 8  1 63 32 33  2 55  4 16 40]
 [59 27 68 14 95 53 34 27 93 95]
 [36 75 16 50 90 30  4 76 47 18]
 [34 39  3 84 98 51 53 43 48 20]
 [97 96 37 22 44 64 11 64 73 94]
 [11 58 84 49 33 61 99 67  5 28]
 [64 21 30 51 67 94 78 69 11  9]
 [37 61 57 61 23 62 37 46 33 51]
 [27  2 55 97 81 26 16  1 93 30]]


In [ ]:
mask2 = ((tmp3%2)==0)
# print(mask2)
elepar = tmp3[mask2]

print("Elementos pares:")
print(elepar)

Elementos pares:
[70 58 22 42 44 76  8 32  2  4 16 40 68 14 34 36 16 50 90 30  4 76 18 34
 84 98 48 20 96 22 44 64 64 94 58 84 28 64 30 94 78 62 46  2 26 16 30]


In [ ]:
tmp4=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp4.dtype)
print(tmp4)

float64
[1. 2. 3. 4. 5.]


In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x)
print(y)
print('SUMA')
print(np.add(x,y))
print('RESTA')
print(np.subtract(x,y))
print('MULTIPLICACION')
print(np.multiply(x,y))
print('DIVISION')
print(np.divide(x,y))
print('RAIZ')
print(np.sqrt(x))
print('POTENCIA')
print(np.power(x,y))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
SUMA
[[ 6  8]
 [10 12]]
RESTA
[[-4 -4]
 [-4 -4]]
MULTIPLICACION
[[ 5 12]
 [21 32]]
DIVISION
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
RAIZ
[[1.         1.41421356]
 [1.73205081 2.        ]]
POTENCIA
[[    1    64]
 [ 2187 65536]]


In [ ]:
tmp5=np.random.randint(1,10, size=(2,5))
print(tmp5)
aux=tmp5.mean()
print(aux)

[[4 7 9 7 2]
 [1 8 6 9 2]]
5.5


In [ ]:
print(tmp5.mean(axis=1))
print(tmp5.mean(axis=0))

[5.8 5.2]
[2.5 7.5 7.5 8.  2. ]


In [12]:
import numpy as np
a=np.random.randint(1,10, (3,4))
print(a)

tmp=np.mean(a)
print(tmp)
print(a.mean())

print(a.mean(axis=1))
print(a.mean(axis=0))

aux=a.sum()
print(aux)

medianValue=np.median(a, axis=1)
print(medianValue)


[[6 5 7 4]
 [4 6 6 6]
 [5 6 2 2]]
4.916666666666667
4.916666666666667
[5.5  5.5  3.75]
[5.         5.66666667 5.         4.        ]
59
[5.5 6.  3.5]


In [17]:
#SORTING - ORDENAR
b=np.random.randn(10)
print(b)
print(b.shape)
b.sort()
print(b)

[-0.73627816 -0.86046227  0.22403338  1.27763632  0.14014486 -0.96114778
 -1.80973687  0.64969916  0.20955048  1.94533182]
(10,)
[-1.80973687 -0.96114778 -0.86046227 -0.73627816  0.14014486  0.20955048
  0.22403338  0.64969916  1.27763632  1.94533182]


In [21]:
c=np.array([2,3,4,3,2,2,8])
print(np.unique(c))

[2 3 4 8]


In [32]:
string1=np.array(['Escritorio', 'Silla', 'Mesa'])
string2=np.array(['Mesita', 'Silla', 'Escritorio'])
tmp1=np.intersect1d(string1, string2)
print(tmp1)
tmp2=np.union1d(string1, string2)
print(tmp2)
print(np.setdiff1d(string1, string2))
print(np.in1d(string1, string2))


['Escritorio' 'Silla']
['Escritorio' 'Mesa' 'Mesita' 'Silla']
['Mesa']
[ True  True False]


In [43]:
#BROADCASTING

aux = np.zeros((4, 3))
print(aux)

replicate=np.array([1,2,1])
aux=aux+replicate
print(aux)

replicateCol=np.array([[10,10,10]])
print(replicateCol.shape)
replicateCol=np.reshape(replicateCol, (3,1))
print(replicateCol.shape)
aux = np.zeros((3, 3))
aux1=aux+replicateCol
print(aux1)

print('WE ARE HERE...')
vector=np.array([45])
matrixZeros=np.zeros((5,5))
print(matrixZeros)
print(matrixZeros+vector)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
(1, 3)
(3, 1)
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
WE ARE HERE...
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
